version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: yarn start
    volumes:
      - .:/usr/app
    networks:
      - node-network
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
      --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER
      --explicit_defaults_for_timestamp
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - node-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
